### ISSUE TITLE
Do we really need a list of availability zones as a required parameter?

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/terraform-aws-ec2-spot-price#1]
How about making availability zones list an optional argument and using all availability zones if nothing is provided?

**Comment by cageyv** [comment]
Some Availability Zones do not have a spot price for some reason
The API says there are no prices available
` Error: no EC2 Spot Price History found matching criteria; try different search`
The AWS Managed Console shows a similar picture

![Selection_20210118_0001](https://user-images.githubusercontent.com/51059484/104857778-5b0f1100-594d-11eb-9af3-bab02ff0fb30.jpg)
![Selection_20210118_0002](https://user-images.githubusercontent.com/51059484/104857779-5cd8d480-594d-11eb-827a-3385235aa701.jpg)

If we send a request without specifying AZ and there is no price in at least one AZ, the same error will occur.
The AWS documentation says this parameter is optional. Probably a bug in the terraform provider.

**Comment by cageyv** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/17446

**Comment by cageyv** [comment]
May help filter out instance types that are not available in the region/az

```hcl
data "aws_ec2_instance_type_offerings" "example" {
  filter {
    name   = "instance-type"
    values = ["t3a.micro"]
  }
  filter {
    name   = "location"
    values = [data.aws_availability_zones.available.names[0]]
  }
  location_type = "availability-zone"
}
```
